name: compound-heatwave-trends
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=2.0.2
  - pandas=2.3.2
  - xarray=2024.7.0
  - scipy=1.13.1
  - scikit-learn=1.6.1
  - matplotlib=3.9.4
  - cartopy=0.23.0
  - joblib=1.5.1
  - netcdf4=1.7.2
  - seaborn=0.13.2
  - regionmask=0.12.1
  - numba=0.60.0
  - xesmf=0.8.10
  - metpy=1.6.3
  - cdo
  - pip
  - pip:
      - geocat-viz==2024.3.0
      - cmaps==2.0.1
      - sacpy==0.0.24
      - MiniSom==2.3.5
